module.exports = {
  "ISSUER_NAME": "",
  "ISSUER_ADDRESS_LINE_1": "",
  "ISSUER_ADDRESS_LINE_2": "",
  "ISSUER_ADDRESS_LINE_3": "",
  "CLIENT_NAME": "",
  "CLIENT_ADDRESS_LINE_1": "",
  "CLIENT_ADDRESS_LINE_2": "",
  "CLIENT_ADDRESS_LINE_3": "",
  "INVOICE_NUMBER": "",
  "INVOICE_DUE_DAY": "",
  "INVOICE_CURRENCY": ""
}